### ISSUE TITLE
General clean-up

### ISSUE THREAD

**Issue by GiovanniSena** [GiovanniSena/LSFM#1]
1. Remove unused files (e.g. the Misc folder?)
2. Remove old / unnecessary comments
3. Remove redundant/old versions of the same function (e.g. FindTransMatlab in Tracking folder?)
4. Add comments in GitHub?

**Comment by PaoloGB** [comment]
1) I am going through each folder and cleaning up the files, removing those not needed. I consider not needed a file that is never called in the code.
2) In progress.
3) In progress although this would be done more efficiently on your side: it has been more than one year since I last used the code. Some things have changed and I might not be 100% up-to-date.
4) GitHub is not really the place to add comments to the code, only comments relative to new features and bug fixing. I am tiding up the comments in the files and adding a short description of each function at the beginning.

**Comment by GiovanniSena** [comment]
Sounds excellent, many thanks Paolo!

**Comment by PaoloGB** [comment]
I just finished revising all the files in the repository.
For each of them I wrote at least a minimal description, tidied up the code and commented.

I **did not** add/remove features (apart from the **webcam** one, as discussed).

The only folder that is still a little messy is the Analysis one. Those files are not necessary for the GUI code with one exception: 

**bgrcheck.m is** used in several parts of the code so it must be visible somewhere from within the GUI code.

I leave it to you and Todd to decide what to do. If you move it (for instance into the tracking folder) then I think you can safely get rid of the Analysis folder. The files in there were only useful for the analysis of beads images but I guess if anyone ever downloads the code, they will have to write their own files.

I have opened a new issue regarding the files that were renamed by GS and RR: from what I gather the differences are only cosmetics. However, I had to rename the functions within them to make them consistent with the file names. See the other issues for details.
