### ISSUE TITLE
Collision check

### ISSUE THREAD

**Issue by GiovanniSena** [GiovanniSena/LSFM#4]
Has the collision check routine been updated since we changed objective?
We probably need to add a parameter in Config to tell the software which objective we intend to use (with pre-assigned values for collision check, etc)

**Comment by ricorandall** [comment]
Yes, I update it with the new value. A new value will also have to be determined for the other objective, because we reassembled arm 2.

**Comment by PaoloGB** [comment]
The parameter "safeDist" in the config file takes into account the objective. When you change the objective you need to modify the value to a correct one (to be determined experimentally).

The idea of having a button to select the objective and change the parameter is good but it is not something I can implement easily from my side. I have Matlab (2015) installed but I am missing all the hardware and libraries for the extra components (motors, camera, labjack) so the code does not run on my pc.

If this is something you want to pursue, I will need to talk with the new PhD, so that at the very least he can check the code runs correctly.

**Comment by GiovanniSena** [comment]
sounds good. We will think about this. Thanks
